---
- name: Add redis GPG key for Debian
  apt_key:
    url: https://www.dotdeb.org/dotdeb.gpg
  when: ansible_pkg_mgr == "apt" and ansible_distribution == 'Debian'

- name: Add redis repository for Debian
  apt_repository:
    repo: "deb http://ftp.hosteurope.de/mirror/packages.dotdeb.org/ {{ ansible_distribution_release }} all"
    update_cache: true
  when: ansible_pkg_mgr == "apt" and ansible_distribution == 'Debian'

- name: Add redis repository for Ubuntu
  apt_repository:
    repo: "ppa:chris-lea/redis-server"
    update_cache: true
  when: ansible_pkg_mgr == "apt" and ansible_distribution == 'Ubuntu'

- name: Install redis-server (apt)
  apt:
    name: redis-server
  when: ansible_pkg_mgr == "apt"

- name: Install required packages (pacman)
  pacman:
    name: redis
  when: ansible_pkg_mgr == "pacman"

- name: Install systemd service file
  template:
    src: systemd-redis.service.j2
    dest: /lib/systemd/system/redis.service
  notify: Reload systemd daemon

- name: Remove redis-server.service
  file:
    state: absent
    path: /lib/systemd/system/redis-server.service

- name: Copy Redis conf 
  template:
    src: redis.conf.j2
    dest: /etc/redis/redis.conf
    owner: root
    group: root
    mode: 0644
  when: ansible_pkg_mgr == "apt"
  notify: Restart redis

- name: Copy Redis conf
  template:
    src: redis.conf.j2
    dest: /etc/redis.conf
    owner: root
    group: root
    mode: 0644
  when: ansible_pkg_mgr == "pacman"
  notify: Restart redis
