---
- name: Add redis ppa
  apt_repository:
    repo: "ppa:chris-lea/redis-server"
  when: ansible_pkg_mgr == "apt" and ansible_distribution == 'Ubuntu'

- name: Add a gpg key
  apt_key:
    url: https://www.dotdeb.org/dotdeb.gpg
  when: ansible_pkg_mgr == "apt" and ansible_distribution == 'Debian' and ansible_distribution_major_version is version('9', '<=')

- name: Add repositoy for current redis packages
  apt_repository:
    repo: "deb http://ftp.hosteurope.de/mirror/packages.dotdeb.org/ {{ ansible_distribution_release }} all"
  when: ansible_pkg_mgr == "apt" and ansible_distribution == 'Debian' and ansible_distribution_major_version is version('9', '<=')

- name: Create Redis Directory
  file:
    path: /etc/redis
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy Redis conf
  template:
    src: redis.conf.j2
    dest: /etc/redis/redis.conf
    owner: root
    group: root
    mode: 0644
  when: ansible_pkg_mgr == "apt"
  notify: Restart redis

- name: Install redis-server (apt)
  apt:
    name: redis-server
  when: ansible_pkg_mgr == "apt"

- name: Install systemd service file
  template:
    src: systemd-redis.service.j2
    dest: /lib/systemd/system/redis.service
  notify: Reload systemd daemon

- name: Remove redis-server.service
  file:
    state: absent
    path: /lib/systemd/system/redis-server.service
